"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Check, CircleHelp, ExternalLink, FileQuestion, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import {
  DATA_CHECKLIST_2025, createBlankFieldWorkpaper, getFieldGuidance, getPageGuidance,
  type ChecklistStatus, type DataConfidence, type GuidedFieldStatus, type GuidedFieldWorkpaper,
  type GuidedReviewState,
} from "@/data/guided-review/2025";

type TaxLine = { lineId:string; formNumber?:string; sectionName?:string; lineNumber?:string; description?:string; inputType?:string; jurisdiction?:string };
type AmountRecord = { cpaAmount?:number|null; internalAmount?:number|null; cpaText?:string; internalText?:string };
type AskPayload = { lineId:string; topic:string; question:string; background:string; priority:"low"|"medium"|"high" };

const statusLabels:Record<GuidedFieldStatus,string> = {
  not_started:"Not Started", data_collected:"Data Collected", calculated:"Calculated", reconciled:"Reconciled",
  difference_identified:"Difference Identified", question_for_tax_firm:"Question for Tax Firm",
  reviewed_no_issue:"Reviewed – No Issue", reviewed_explained:"Reviewed – Difference Explained",
  potential_error:"Potential Error", not_applicable:"N/A",
};
const checklistLabels:Record<ChecklistStatus,string> = { pending:"Pending", ready:"Ready", missing:"Missing", not_applicable:"Not Applicable", tax_firm_support:"Need Tax Firm Support" };
const parseAmount = (value:string) => value.trim() === "" ? null : Number(value.replace(/,/g,""));
const amount = (value:number|null|undefined) => value === null || value === undefined ? "—" : new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const hasWorkpaper = (item?:GuidedFieldWorkpaper) => Boolean(item && (item.sourceFile || item.sourceReport || item.glAccount || item.bookAmount !== null || item.taxAmount !== null || item.notes || item.missing || item.reviewStatus !== "not_started"));

export function guidedReviewMetrics(state:GuidedReviewState) {
  const documents = DATA_CHECKLIST_2025.map(([id]) => state.documents[id]?.status ?? "pending");
  const fields = Object.values(state.fields);
  return {
    ready:documents.filter(status => status === "ready").length,
    missingDocuments:documents.filter(status => status === "missing").length,
    taxFirmSupport:documents.filter(status => status === "tax_firm_support").length,
    fieldsReviewed:fields.filter(item => ["reconciled","reviewed_no_issue","reviewed_explained","not_applicable"].includes(item.reviewStatus)).length,
    missingFields:fields.filter(item => item.missing).length,
    openDifferences:fields.filter(item => ["difference_identified","potential_error"].includes(item.reviewStatus)).length,
  };
}

function GuidanceDetails({ line }:{line:TaxLine}) {
  const guide = getFieldGuidance(line);
  const page = getPageGuidance(line.formNumber);
  return <div className="guidance-details">
    <section className="page-guidance-card"><span>LEVEL 1 · PAGE GUIDANCE</span><h3>Form {line.formNumber}</h3><p>{page.purpose}</p><dl><div><dt>When required</dt><dd>{page.required}</dd></div><div><dt>Key sources</dt><dd>{page.sources.join(" · ")}</dd></div><div><dt>Main adjustments</dt><dd>{page.adjustments.join(" · ")}</dd></div><div><dt>Key reconciliation</dt><dd>{page.reconciliations.join(" · ")}</dd></div><div><dt>Common risks</dt><dd>{page.risks.join(" · ")}</dd></div></dl></section>
    <section><span>LEVEL 2 · SECTION GUIDANCE</span><h3>{line.sectionName || "Return section"}</h3><p>Review the section as a complete accounting and tax flow. Confirm that subtotals, supporting forms, and downstream return lines use the same scope.</p></section>
    <section><span>LEVEL 3 · FIELD GUIDANCE</span><h3>{guide.title}</h3><GuideItem label="What is this?" value={guide.what} />
      <GuideList label="Data scope" values={guide.scope} /><GuideList label="Primary data source" values={guide.primarySources} />
      <GuideList label="Secondary data source" values={guide.secondarySources} /><GuideItem label="Book or tax?" value={guide.amountType} />
      <GuideItem label="Tax treatment" value={guide.taxTreatment} /><GuideList label="Reconciliation" values={guide.reconciliation} />
      <GuideList label="Common errors" values={guide.commonErrors} /><GuideItem label="Suggested question for Tax Firm" value={guide.suggestedQuestion} />
    </section>
    <section><span>WHERE DOES THIS NUMBER COME FROM?</span><h3>Source locator</h3><GuideList label="Suggested GL accounts" values={guide.suggestedAccounts} /><GuideList label="Supporting documents" values={guide.supportingDocuments} /></section>
    <footer><a href={guide.sourceUrl} target="_blank" rel="noreferrer">{guide.source} <ExternalLink /></a><small>Tax year 2025 · last verified {guide.lastVerified}</small></footer>
  </div>;
}
function GuideItem({label,value}:{label:string;value:string}) { return <div className="guide-item"><strong>{label}</strong><p>{value}</p></div>; }
function GuideList({label,values}:{label:string;values:string[]}) { return <div className="guide-item"><strong>{label}</strong><ul>{values.map(value => <li key={value}>{value}</li>)}</ul></div>; }

export function FieldGuidanceDrawer({ line, workpaper, reviewer, onChange, onAsk }:{line:TaxLine;workpaper?:GuidedFieldWorkpaper;reviewer:string;onChange:(patch:Partial<GuidedFieldWorkpaper>)=>void;onAsk:(payload:AskPayload)=>void}) {
  const [open,setOpen] = useState(false);
  const item = { ...createBlankFieldWorkpaper(reviewer), ...(workpaper ?? {}) };
  const guide = getFieldGuidance(line);
  const bridgeAmount = item.bookAmount === null ? null : item.bookAmount + (item.permanentDifference ?? 0) + (item.temporaryDifference ?? 0) + (item.priorYearAdjustment ?? 0) + (item.taxAdjustment ?? 0);
  const ask = () => onAsk({lineId:line.lineId,topic:`${line.formNumber} · ${line.description}`,question:guide.suggestedQuestion,background:`Guided review · Tax year 2025\nSource file: ${item.sourceFile || "Not identified"}\nGL account: ${item.glAccount || "Not identified"}\nReviewer note: ${item.notes || "None"}`,priority:item.reviewStatus === "potential_error" ? "high" : "medium"});
  return <>
    <div className="guidance-shortcuts"><Button size="xs" variant="outline" onClick={() => setOpen(true)}><CircleHelp />How do I fill this?</Button><Button size="xs" variant="ghost" onClick={() => setOpen(true)}><Search />Where does this number come from?</Button></div>
    <Sheet open={open} onOpenChange={setOpen}><SheetContent className="guidance-sheet sm:max-w-2xl"><SheetHeader><SheetTitle>{line.formNumber} · Line {line.lineNumber} · Reviewer Guidance</SheetTitle><SheetDescription>{line.description} · Tax year 2025</SheetDescription></SheetHeader><div className="guidance-sheet-scroll"><GuidanceDetails line={line} />
      <section className="field-workpaper"><span>DATA LINEAGE & REVIEW</span><h3>Document this number</h3><div className="two-col"><Field label="Source file"><Input value={item.sourceFile} onChange={e=>onChange({sourceFile:e.target.value})} placeholder="File name / folder" /></Field><Field label="Source report"><Input value={item.sourceReport} onChange={e=>onChange({sourceReport:e.target.value})} placeholder="TB, GL, schedule…" /></Field></div><Field label="GL account(s)"><Input value={item.glAccount} onChange={e=>onChange({glAccount:e.target.value})} placeholder={guide.suggestedAccounts.join(", ")} /></Field>
        <div className="bridge-input-grid"><Field label="Book amount"><Input value={item.bookAmount ?? ""} onChange={e=>onChange({bookAmount:parseAmount(e.target.value)})} /></Field><Field label="Permanent difference"><Input value={item.permanentDifference ?? ""} onChange={e=>onChange({permanentDifference:parseAmount(e.target.value)})} /></Field><Field label="Temporary difference"><Input value={item.temporaryDifference ?? ""} onChange={e=>onChange({temporaryDifference:parseAmount(e.target.value)})} /></Field><Field label="Prior-year adjustment"><Input value={item.priorYearAdjustment ?? ""} onChange={e=>onChange({priorYearAdjustment:parseAmount(e.target.value)})} /></Field><Field label="Current-year tax adjustment"><Input value={item.taxAdjustment ?? ""} onChange={e=>onChange({taxAdjustment:parseAmount(e.target.value)})} /></Field><Field label="Tax return amount"><Input value={item.taxAmount ?? ""} onChange={e=>onChange({taxAmount:parseAmount(e.target.value)})} /></Field></div>
        <div className="bridge-result"><span>Calculated bridge amount</span><strong>{amount(bridgeAmount)}</strong><small>Book + permanent + temporary + prior-year + current-year adjustments</small></div>
        <div className="two-col"><Field label="Supporting form"><Input value={item.supportingForm} onChange={e=>onChange({supportingForm:e.target.value})} placeholder={`Form ${line.formNumber}`} /></Field><Field label="Target Form 1120 line"><Input value={item.targetLine} onChange={e=>onChange({targetLine:e.target.value})} placeholder="Reconciliation target" /></Field><Field label="Reviewer"><Input value={item.reviewer} onChange={e=>onChange({reviewer:e.target.value})} /></Field><Field label="Review date"><Input type="date" value={item.reviewDate} onChange={e=>onChange({reviewDate:e.target.value})} /></Field><Field label="Review status"><NativeSelect value={item.reviewStatus} onChange={e=>onChange({reviewStatus:e.target.value as GuidedFieldStatus})}>{Object.entries(statusLabels).map(([value,label])=><NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></Field><Field label="Data confidence"><NativeSelect value={item.confidence} onChange={e=>onChange({confidence:e.target.value as DataConfidence})}><NativeSelectOption value="">Select</NativeSelectOption><NativeSelectOption value="high">High Confidence</NativeSelectOption><NativeSelectOption value="medium">Medium Confidence</NativeSelectOption><NativeSelectOption value="low">Low Confidence</NativeSelectOption><NativeSelectOption value="tax_firm">Tax Firm Provided</NativeSelectOption></NativeSelect></Field></div>
        <Field label="Reviewer note"><Textarea value={item.notes} onChange={e=>onChange({notes:e.target.value})} placeholder="Scope, calculation, exception, or conclusion" /></Field><label className="missing-toggle"><Checkbox checked={item.missing} onCheckedChange={checked=>onChange({missing:checked===true,reviewStatus:checked===true?"question_for_tax_firm":item.reviewStatus})} /><span><strong>I don’t know this amount / data is missing</strong><small>Mark as pending and use the suggested sources or ask the tax firm.</small></span></label><Button onClick={ask}><FileQuestion />Add suggested question for Tax Firm</Button>
      </section></div></SheetContent></Sheet>
  </>;
}

export function GuidedReview({taxYear,company,reviewer,state,lines,onChange,onOpenLine,onAsk}:{taxYear:number;company:string;reviewer:string;state:GuidedReviewState;lines:TaxLine[];records:Record<string,AmountRecord>;onChange:(state:GuidedReviewState)=>void;onOpenLine:(lineId:string)=>void;onAsk:(payload:AskPayload)=>void}) {
  const [view,setView] = useState<"prepare"|"guidance"|"lineage"|"bridge"|"missing">("prepare");
  const [search,setSearch] = useState("");
  const metrics = guidedReviewMetrics(state);
  const searchable = useMemo(()=>lines.filter(line => `${line.formNumber} ${line.lineNumber} ${line.sectionName} ${line.description} ${getFieldGuidance(line).primarySources.join(" ")} ${getFieldGuidance(line).suggestedAccounts.join(" ")}`.toLowerCase().includes(search.toLowerCase())).slice(0,80),[lines,search]);
  const workpapers = lines.map(line=>({line,item:state.fields[line.lineId]})).filter(({item})=>hasWorkpaper(item));
  const missing = workpapers.filter(({item})=>item?.missing || ["difference_identified","question_for_tax_firm","potential_error"].includes(item?.reviewStatus ?? ""));
  const updateDocument = (id:string,patch:Record<string,unknown>) => { const current=state.documents[id]??{status:"pending" as ChecklistStatus,source:"",notes:"",available:false}; onChange({...state,documents:{...state.documents,[id]:{...current,...patch}}}); };
  if (taxYear !== 2025) return <main className="page"><div className="state-caution"><AlertTriangle /><span><strong>No approved guided-review rule set exists for {taxYear}.</strong><br/>Add and verify a separate tax-year configuration before using line guidance.</span></div></main>;
  return <main className="page guided-page"><div className="page-heading"><div><p className="eyebrow">GUIDED TAX RETURN REVIEW · {taxYear}</p><h1>引导式税务申报复核</h1><p>{company} · Prepare data, trace every number, document tax adjustments, and identify what to ask the tax firm.</p></div></div>
    <section className="guided-flow"><span>Prepare Data</span><b>→</b><span>Map Accounting Data</span><b>→</b><span>Review Tax Fields</span><b>→</b><span>Reconcile</span><b>→</b><span>Ask Tax Firm</span></section>
    <section className="guided-metrics"><article><span>Data ready</span><strong>{Math.round(metrics.ready/DATA_CHECKLIST_2025.length*100)}%</strong><small>{metrics.ready} of {DATA_CHECKLIST_2025.length} items</small></article><article className={metrics.missingDocuments?"attention":""}><span>Missing documents</span><strong>{metrics.missingDocuments}</strong><small>{metrics.taxFirmSupport} need tax firm support</small></article><article><span>Fields documented</span><strong>{workpapers.length}</strong><small>{metrics.fieldsReviewed} reviewed</small></article><article className={metrics.openDifferences?"attention":""}><span>Open differences</span><strong>{metrics.openDifferences}</strong><small>Adjustment or error review</small></article><article className={metrics.missingFields?"attention":""}><span>Missing field data</span><strong>{metrics.missingFields}</strong><small>Use missing-data guidance</small></article></section>
    <nav className="guided-tabs">{[["prepare","Pre-filing Data"],["guidance","Field Guidance"],["lineage","Data Lineage"],["bridge","Adjustment Bridge"],["missing","Missing Data"]].map(([key,label])=><button key={key} className={view===key?"active":""} onClick={()=>setView(key as typeof view)}>{label}</button>)}</nav>
    {view==="prepare"&&<section className="guided-panel"><div className="panel-head"><div><span className="jurisdiction">PRE-FILING DATA CHECKLIST</span><h2>填报前资料准备清单</h2><p>Confirm the document set before relying on the return package. A missing document is not the same as Not Applicable.</p></div></div><div className="table-wrap checklist-table"><table><thead><tr><th>Document</th><th>Tax year</th><th>Expected source</th><th>Status</th><th>Available?</th><th>Related forms</th><th>Notes</th></tr></thead><tbody>{DATA_CHECKLIST_2025.map(([id,name,source,forms])=>{const saved=state.documents[id];const item={status:saved?.status??("pending" as ChecklistStatus),source:saved?.source??"",notes:saved?.notes??"",available:saved?.available??false};return <tr key={id} className={item.status==="missing"?"missing-row":""}><td><strong>{name}</strong></td><td>2025</td><td><Input value={item.source} onChange={e=>updateDocument(id,{source:e.target.value})} placeholder={source}/></td><td><NativeSelect value={item.status} onChange={e=>updateDocument(id,{status:e.target.value as ChecklistStatus})}>{Object.entries(checklistLabels).map(([value,label])=><NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></td><td><label className="received-check"><Checkbox checked={item.available} onCheckedChange={checked=>updateDocument(id,{available:checked===true,status:checked===true&&item.status==="pending"?"ready":item.status})}/>{item.available?"Available":"Not available"}</label></td><td>{forms}</td><td><Input value={item.notes} onChange={e=>updateDocument(id,{notes:e.target.value})} placeholder="File name, owner, follow-up"/></td></tr>})}</tbody></table></div></section>}
    {view==="guidance"&&<section className="guided-panel"><div className="panel-head"><div><span className="jurisdiction">SEARCH TAX REVIEW GUIDANCE</span><h2>Find a form, field, account, or tax concept</h2></div></div><label className="guidance-search"><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try Inventory, Depreciation, Related party, Interest, COGS…"/></label><div className="guidance-results">{searchable.map(line=>{const guide=getFieldGuidance(line);return <article key={line.lineId}><div><span>{line.jurisdiction} · FORM {line.formNumber} · LINE {line.lineNumber}</span><h3>{line.description}</h3><p><strong>{guide.amountType}</strong> · {guide.what}</p><small>Recommended source: {guide.primarySources.join(" · ")}</small></div><Button variant="outline" onClick={()=>onOpenLine(line.lineId)}>Open field</Button></article>})}</div></section>}
    {view==="lineage"&&<section className="guided-panel"><div className="panel-head"><div><span className="jurisdiction">DATA LINEAGE</span><h2>Source data → tax return</h2><p>Field workpapers are created from the “How do I fill this?” drawer on each return line.</p></div></div>{workpapers.length?<div className="table-wrap lineage-table"><table><thead><tr><th>Form / field</th><th>Source file / report</th><th>GL account</th><th>Book amount</th><th>Tax adjustment</th><th>Tax amount</th><th>Supporting form → target</th><th>Reviewer / status</th></tr></thead><tbody>{workpapers.map(({line,item})=><tr key={line.lineId} onClick={()=>onOpenLine(line.lineId)}><td><strong>{line.formNumber} · {line.lineNumber}</strong><small>{line.description}</small></td><td>{item?.sourceFile||"—"}<small>{item?.sourceReport}</small></td><td>{item?.glAccount||"—"}</td><td>{amount(item?.bookAmount)}</td><td>{amount((item?.permanentDifference??0)+(item?.temporaryDifference??0)+(item?.priorYearAdjustment??0)+(item?.taxAdjustment??0))}</td><td>{amount(item?.taxAmount)}</td><td>{item?.supportingForm||"—"}<small>{item?.targetLine}</small></td><td>{item?.reviewer||reviewer}<small>{item?statusLabels[item.reviewStatus]:"Not Started"}</small></td></tr>)}</tbody></table></div>:<EmptyState title="No data lineage recorded" text="Open a return line and select “How do I fill this?” to document its source and calculation."/>}</section>}
    {view==="bridge"&&<section className="guided-panel"><div className="panel-head"><div><span className="jurisdiction">BOOK-TO-TAX ADJUSTMENT BRIDGE</span><h2>Field-level accounting to tax bridge</h2><p>Positive and negative adjustments should follow the documented reviewer convention and tie to the return amount.</p></div></div>{workpapers.filter(({item})=>item?.bookAmount!==null).length?<div className="table-wrap lineage-table"><table><thead><tr><th>Field</th><th>Book</th><th>Permanent</th><th>Temporary</th><th>Prior year</th><th>Current year</th><th>Bridge result</th><th>Return amount</th><th>Difference</th></tr></thead><tbody>{workpapers.filter(({item})=>item?.bookAmount!==null).map(({line,item})=>{const bridge=(item?.bookAmount??0)+(item?.permanentDifference??0)+(item?.temporaryDifference??0)+(item?.priorYearAdjustment??0)+(item?.taxAdjustment??0);const diff=item?.taxAmount===null?null:bridge-(item?.taxAmount??0);return <tr key={line.lineId} className={diff!==null&&Math.abs(diff)>=1?"missing-row":""} onClick={()=>onOpenLine(line.lineId)}><td><strong>{line.formNumber} · {line.lineNumber}</strong><small>{line.description}</small></td><td>{amount(item?.bookAmount)}</td><td>{amount(item?.permanentDifference)}</td><td>{amount(item?.temporaryDifference)}</td><td>{amount(item?.priorYearAdjustment)}</td><td>{amount(item?.taxAdjustment)}</td><td>{amount(bridge)}</td><td>{amount(item?.taxAmount)}</td><td>{amount(diff)}</td></tr>})}</tbody></table></div>:<EmptyState title="No field-level bridge recorded" text="Enter a book amount and adjustments from a return field's guidance drawer."/>}</section>}
    {view==="missing"&&<section className="guided-panel"><div className="panel-head"><div><span className="jurisdiction">MISSING DATA GUIDANCE</span><h2>I don’t know this amount</h2><p>Use the recommended source, identify who owns the information, and send a structured question instead of leaving an unexplained blank.</p></div></div>{missing.length?<div className="missing-list">{missing.map(({line,item})=>{const guide=getFieldGuidance(line);return <article key={line.lineId}><AlertTriangle/><div><span>FORM {line.formNumber} · LINE {line.lineNumber}</span><h3>{line.description}</h3><p>Recommended: {guide.primarySources.join(" · ")}</p><small>Possible accounts: {guide.suggestedAccounts.join(" · ")}</small></div><div><Button variant="outline" onClick={()=>onOpenLine(line.lineId)}>Open field</Button><Button onClick={()=>onAsk({lineId:line.lineId,topic:`${line.formNumber} · Missing data`,question:guide.suggestedQuestion,background:`Missing data guidance · ${item?.notes||"No reviewer note"}`,priority:"medium"})}><FileQuestion/>Ask Tax Firm</Button></div></article>})}</div>:<EmptyState title="No missing field data marked" text="Use “I don’t know this amount” in any field guidance drawer when data cannot be confirmed."/>}</section>}
  </main>;
}

function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="field"><span>{label}</span>{children}</label>; }
function EmptyState({title,text}:{title:string;text:string}) { return <div className="guided-empty"><Check/><strong>{title}</strong><p>{text}</p></div>; }
